djangocc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^flashcards/', include('flashcards.urls', namespace='flashcards')),
    url(r'^admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>uStudy</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" class="w3-circle"
    href="https://bit.ly/2MP30xY" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://fonts.googleapis.com/css2?family=Amiri:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel='stylesheet' href="{% static 'css/style.css' %}" />
    
  </head>
  <style>
 
    
    .overlay {
      height: 100%;
      width: 0;
      position: fixed;
      z-index: 100;
      top: 0;
      left: 0;
      background-color: rgb(0,0,0);
      background-color: rgba(0,0,0, 0.9);
      overflow-x: hidden;
      transition: 0.5s;
    }
    
    .overlay-content {
      position: relative;
      top: 25%;
      width: 100%;
      text-align: center;
      margin-top: 30px;
    }
    
    .overlay a {
      padding: 8px;
      text-decoration: none;
      font-size: 36px;
      color: #818181;
      display: block;
      transition: 0.3s;
    }
    .carousel-inner img {
      border-radius: 15px;
      width: 100%;
      height: 300px;
  }
    .overlay a:hover, .overlay a:focus {
      color: #f1f1f1;
    }
    
    .overlay .closebtn {
      position: absolute;
      top: 20px;
      right: 45px;
      font-size: 60px;
    }
    nav a{
      color: black;
      text-decoration: none;
      font-size: 1.25em;
      padding: 5px;
    }
    body {
      margin: 0;
      font-family: 'Yatra One', cursive;
      /*  background-image: url(https://bit.ly/2uz4VkJ); */
      background-image: url("https://bit.ly/2xUuL4s");
       background-attachment: fixed;
       background-size: cover;
    }
    
    nav {
      /*background: burlywood;*/
      background: yellow;
      padding: 5px;
      border-radius: 5px;
    }
    
    nav a{
      color: black;
      text-decoration: none;
      font-size: 1.25em;
      padding: 5px;
    }
    h1,h4{
      color:coral;
    }
    #j{
    color:black;
    font-weight: bolder;
    z-index: 95;
    }
    h3{
      font-weight: bolder;
      font-size: x-large;
      color: gray;
    }
    .container{
      width: 80%;
      min-width: 400px;
      margin: 0 auto;
    }
    
    .homepage-banner{
      text-align: center;
      color: black;
      font-size: 2em;
      max-width: 100%;
      font-family: 'Amiri', serif;
    }
    
    .homepage-banner hr{
      width: 20%;
    }
    
    .my-button {
      display: block;
      width: 200px;
      margin: 10px auto;
      background-color:rgba(0,0,0, 0.9);
      border: none;
      border-radius: 10px;
      color: white;
      text-align: center;
      text-decoration: none;
    
    }
    a:hover,a:focus{
      text-decoration: none;
      color: yellow;
    }
    .blue-background {
      background: rgb(32, 178, 170,0.9);
      text-decoration: none;
      color:grey;
    }
    a{
      text-decoration: none;
    }
    
    .deck-header{
      margin-top: 20px;
      display: block;
      overflow: auto;
    }
    
    .deck-header-title{
      float: left;
      width: 50%;
      color: green;
    }
    
    .deck-header-title h1{
      margin: 0;
    }
    
    .deck-header-actions{
      float: right;
      width: 50%;
      color: red;
      text-align: right;
    }
    
    @media screen and (max-height: 450px) {
      .overlay a {font-size: 20px}
      .overlay .closebtn {
      font-size: 40px;
      top: 15px;
      right: 35px;
      }
    }

    body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
  position: relative;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
   /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
  box-sizing: border-box;
  
  z-index: 100;
}

/* Modal Content/Box */
.modal-content {
  background-color: rgba(0,0,0,0.4);
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}

/* Add Zoom Animation */
.animate {
  -webkit-animation: animatezoom 0.6s;
  animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
  from {-webkit-transform: scale(0)} 
  to {-webkit-transform: scale(1)}
}
  
@keyframes animatezoom {
  from {transform: scale(0)} 
  to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}



    </style>
  <body>
    <div class='container'>
      <div id="myNav" class="overlay">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <div class="overlay-content">
          <a class="fa fa-home" href="{% url 'home' %}"> Study</a> |
          <a class="fa fa-bars" href="{% url 'flashcards:home' %}"> Decks</a> |
          <a class="fa fa-info" href=""> About</a> |
          <a class="fa fa-phone" href=""> Contact</a>
          {% if request.user.is_superuser %}
            | <a class="fa fa-admin" href="{% url 'admin:index' %}">Admin Panel</a>
          {% endif %}
        </div>
      </div>
      <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; open</span>

      <nav>
      
      </nav>

      {% block content %}
      {% endblock %}
    </div>
    <script>
      function openNav() {
        document.getElementById("myNav").style.width = "100%";
      }
      
      function closeNav() {
        document.getElementById("myNav").style.width = "0%";
      }
      </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class='homepage-banner'>
    <h1>Study</h1>
    <hr>
    <h4>Reading with a helping Hand!</h4> <img src="https://bit.ly/2MP30xY" width="50" style="border-radius:50%;">
    <a class='my-button' class="nav-link" href="{% url 'flashcards:home' %}">Get Started</a>
</div>
<div id="carouselId" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselId" data-slide-to="0" class="active"></li>
        <li data-target="#carouselId" data-slide-to="1"></li>
        <li data-target="#carouselId" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img src="https://bit.ly/2UxEplx" alt="First slide">


            <div class="carousel-caption d-none d-md-block">
                <h3>Read well</h3>
                <p id="j"> Eat Food and drink alot of water</p>

            </div>
        </div>
        <div class="carousel-item">
            <img src="https://bit.ly/3hqdAK6" alt="Second slide">

            <div class="carousel-caption d-none d-md-block">


                <h3>Find Kata</h3>
                <p id="j">No pain no gain</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://bit.ly/3hd2E2p" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h3>Read smart</h3>
                <p id="j">Be happy and meet friends</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselId" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselId" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>

<div id="id01" class="modal">

    <form class="modal-content animate" action="/action_page.php" method="post">
        <div class="imgcontainer">
            <p style="font-weight: bolder; color:white;">Aleardy logged in!</p>
            <span onclick="document.getElementById('id01').style.display='none'" class="close"
                title="Close Modal">&times;</span>
            <img src="https://bit.ly/2AXEtnZ" style="border-radius: 50%; height:100px; width:100px;" alt="Avatar"
                class="avatar">
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-md-6" style="background-color:yellow;">
                    <h1>Sign in</h1>
                    <label for="uname"><b>Username</b></label>
                    <input type="text" placeholder="Enter Username" name="uname" required>

                    <label for="psw"><b>Password</b></label>
                    <input type="password" placeholder="Enter Password" name="psw" required>

                    <button type="submit">Login</button>
                    <label>
                        <input type="checkbox" checked="checked" name="remember"> Remember me
                    </label>
                </div>
                <div class="col-sm-9 col-md-6" style="background-color:grey;">
                    <h1>Sign Up</h1>
                    <p>Please fill in this form to create an account.</p>
                    <hr>
                    <label for="email"><b>Email</b></label>
                    <input type="text" placeholder="Enter Email" name="email" required>

                    <label for="psw"><b>Password</b></label>
                    <input type="password" placeholder="Enter Password" name="psw" required>

                    <label for="psw-repeat"><b>Repeat Password</b></label>
                    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>

                    <label>
                        <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
                    </label>

                    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.
                    </p>
                </div>
            </div>
        </div>

        <div class="container" style="background-color:gba(0,0,0,0.4);">
            <button type="button" onclick="document.getElementById('id01').style.display='none'"
                class="cancelbtn">Cancel</button>
            <span class="psw">Forgot <a href="#">password?</a></span>
        </div>
    </form>
</div>



<script>
    // Get the modal
    var modal = document.getElementById('id01');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
{% endblock %}