djangocc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^flashcards/', include('flashcards.urls', namespace='flashcards')),
    url(r'^admin/', admin.site.urls),
]

flashcards/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'decks/create/', views.createDeck, name='createDeck'),
    url(r'decks/edit/(?P<deck_id>[\d]+)', views.editDeck, name='editDeck'),
    url(r'decks/delete/(?P<deck_id>[\d]+)', views.deleteDeck, name='deleteDeck'),
    url(r'decks/view/(?P<deck_id>[\d]+)', views.viewDeck, name='viewDeck'),
    url(r'cards/create/(?P<deck_id>[\d]+)', views.createCard, name='createCard'),
    url(r'cards/edit/(?P<card_id>[\d]+)', views.editCard, name='editCard'),
    url(r'cards/delete/(?P<card_id>[\d]+)', views.deleteCard, name='deleteCard')
]

flashcards/models.py
from django.db import models

# Create your models here.
class Deck(models.Model):
    title = models.CharField(max_length=64, null=False, blank=False)
    description = models.CharField(max_length=255, null=False, blank=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_number_of_cards(self):
        '''
        Returns the number of cards in the decks related
        card_set
        '''
        return self.card_set.count()
    get_number_of_cards.short_description = 'Card Count'

class Card(models.Model):
    parentDeck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    front = models.TextField()
    back = models.TextField()

    def __str__(self):
        return self.front

flashcards/forms.py
from django.forms import ModelForm
from django import forms
from .models import Deck, Card, Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=80, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
class DeckForm(ModelForm):
    '''
    Form mapping to the deck model
    '''
    class Meta:
        model = Deck
        fields = ['title', 'description', 'is_active']

class CardForm(ModelForm):
    '''
    Form mapping to the card model
    '''
    class Meta:
        model = Card
        fields = ['parentDeck', 'front', 'back']

flashcards/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.generic import ListView, DetailView
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import CardForm, DeckForm,UserRegisterForm
from django.views import generic
from .models import *
from django.db.models import Avg


# Create your views here.
class CardListView(ListView):
    model = Card
    template_name = 'flashcards/createandeditCard.html'


class DeckDetailView(DetailView): 
    model = Deck
    template_name = 'createandeditDeck.html'

    
class SignUpView(generic.CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'
    
def home(request):
    '''
    Renders the FLASHCARD app home template
    '''
    qs = Deck.objects.order_by('-title').filter(is_active=True)
    context = {'decks': qs}
    return render(request, 'flashcards/home.html', context)

def createCard(request, deck_id):
    '''
    Used to create a card for the deck with the given deck_id
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/flashcards')
    else:
        form = CardForm(initial={'parentDeck':deck_obj})
    context = {'form': form}
    return render(request, 'flashcards/createAndEditCard.html', context)

def createDeck(request):
    '''
    Renders the form to add new decks to the database
    '''
    if request.method == 'POST':
        # create the form isntance, and populate with data from the request
        form = DeckForm(request.POST)
        # check if the form is valid
        if form.is_valid():
            #save the form, this saves the object to the database
            form.save()
            return HttpResponseRedirect('/flashcards')
    else:
        form = DeckForm()
    context = {'form': form}
    return render(request, 'flashcards/createAndEditDeck.html', context)

def deleteCard(request, card_id):
    '''
    Deletes the card whose id == card_id
    '''
    card_obj = get_object_or_404(Card, id=card_id)
    card_obj.delete()
    return HttpResponseRedirect('/flashcards')

def deleteDeck(request, deck_id):
    '''
    Deletes the deck whose id == deck_id
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    deck_obj.delete()
    return HttpResponseRedirect('/flashcards')

def editCard(request, card_id):
    '''
    Renders the form to edit information about a card
    '''
    card_obj = get_object_or_404(Card, id=card_id)
    if request.method == 'POST':
        form = CardForm(request.POST, instance=card_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/flashcards')
    else:
        form = CardForm(instance=card_obj)
    context = {'form':form, 'edit_mode':True, 'card_obj':card_obj}
    return render(request, 'flashcards/createAndEditCard.html', context)

def editDeck(request, deck_id):
    '''
    Renders the form to edit information about a deck object
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    if request.method == 'POST':
        # create the form isntance, and populate with data from the request
        form = DeckForm(request.POST, instance=deck_obj)
        # check if the form is valid
        if form.is_valid():
            #save the form, this saves the object to the database
            form.save()
            return HttpResponseRedirect('/flashcards')
    else:
        form = DeckForm(instance=deck_obj)
    context = {'form': form, 'edit_mode':True, 'deck_obj':deck_obj}
    return render(request, 'flashcards/createAndEditDeck.html', context)

def viewDeck(request, deck_id):
    '''
    Gets deck from the database.
    Return first card in deck unless card_id is specified in url
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    card_list = deck_obj.card_set.all()
    card_obj = card_list.first()
    print(deck_obj)
    print(card_list)
    print(card_obj)
    context = {'deck_obj': deck_obj, 'card_obj':card_obj}
    return render(request, 'flashcards/viewDeck.html', context)

flashcards/templates/flashcards/createAndEditCard.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Submit Form">
</form>

{% if edit_mode %}
  <p>Do you want to delete this card?</p>
  <a href="{% url 'flashcards:deleteCard'  card_obj.id %}"> Delete This Card</a>
{% endif %}

{% endblock %}

flashcards/templates/flashcards/createAndEditDeck.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Submit Form">
</form>

{% if edit_mode %}
  <p>Do you want to delete this deck?</p>
  <a href="{% url 'flashcards:deleteDeck' deck_obj.id %}"> Delete This Deck</a>
{% endif %}

{% endblock %}

flashcards/templates/flashcards/createDeck.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Submit Form">
</form>
{% endblock %}

flashcards/templates/flashcards/home.html
{% extends 'base.html' %}
{% block content %}
  <div class='homepage-banner'>
    <h1>Study</h1>
    <hr>
    <h4>Please select a deck below!</h4>
    <div><a class='blue-background my-button' href="{% url 'flashcards:createDeck' %}">Create New Deck</a></div>

      {% if decks %}
          {% for deck in decks %}
            <div><a class='my-button' href="{% url 'flashcards:viewDeck' deck.id %}">{{deck.title}}</a></div>
          {% endfor %}
      {% else %}
        <h1>No Decks Found! Contact an Admin!</h1>
      {% endif %}
  </div>
{% endblock %}

flashcards/templates/flashcards/viewDeck.html
{% extends 'base.html' %}

{% block content %}
<div class="deck-header">
  <div class="deck-header-title">
    <h1>{{deck_obj}}</h1>
  </div>
  <div class="deck-header-actions">
    <a class="w3-button w3-round w3-blue" href="{% url 'flashcards:editDeck' deck_obj.id %}"><b>+ </b>edit deck</a><br><br>
    <a class="w3-button w3-round w3-blue" href="{% url 'flashcards:createCard' deck_obj.id %}"><b>+ </b>add card</a><br><br>
    {% if card_obj %}
      <a class="w3-button w3-round w3-blue" href="{% url 'flashcards:editCard' card_obj.id %}"><b>+ </b>edit current card</a><br> 
    {% endif %}
  </div>
</div>


<hr>
{% if card_obj %}
  <p>{{card_obj.front}}</p>
  <p>{{card_obj.back}}</p>
{% else %}
  <p>No card found. Have you tried to add one?</p>
{% endif %}

{% endblock %}